### ISSUE TITLE
Unknown error while attempting to log a queue time: 'GunicornHookProcessor' object has no attribute 'ds_agent'

### ISSUE THREAD

**Issue by InaamIlahi** [Mjolnir-Software/dynoscale-python#3]
I am getting this error repeatedly on each request: "Unknown error while attempting to log a queue time: 'GunicornHookProcessor' object has no attribute 'ds_agent'". I have been unable to find a solution to this error. I am using this with Django where there are 8 workers.

I have added this to "from dynoscale.hooks.gunicorn import pre_request" to my gunicorn config file.

Dynoscaling is working fine but this error is regularly coming.

**Comment by InaamIlahi** [comment]
Dynoscale can't start GunicornHookProcessor with invalid config: {"DYNO": "web.6", "DYNOSCALE_DEV_MODE": false, "DYNOSCALE_URL": "-------", "redis_urls": {"REDISCLOUD_URL": "redis://default:[Filtered]@r---"}, "repository_path": "/app/dynoscale_repo.sqlite3"}.

**Comment by InaamIlahi** [comment]
the above error comes for all dynos except 0

**Comment by fuho** [comment]
This is expected behavior, only the first web dyno is used to collect data. There is no need to collect data from the other dynos because the load balancer spreads the load evenly.

**Comment by InaamIlahi** [comment]
is there a fix to this? I don't want the error to be caught again and again
